# Data

In [4]:
# colab 경로 설정
from google.colab import drive
drive.mount('/content/dirve')
data_path = '/content/dirve/MyDrive/NAVER boostcamp AI Tech 5기/competitions/RecSys 기초대회/data/'
v_data_path = data_path + 'v7/'

Drive already mounted at /content/dirve; to attempt to forcibly remount, call drive.mount("/content/dirve", force_remount=True).

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
# data_path = '../data/'
# v_data_path='../data/v3/'

path = v_data_path

users = pd.read_csv(path+'users.csv')
books = pd.read_csv(path+'books.csv')
train_ratings = pd.read_csv(path+'train_ratings.csv')
test_ratings = pd.read_csv(path+'test_ratings.csv')

print('users shape: ', users.shape)
print('books shape: ', books.shape)
print('train_ratings shape: ', train_ratings.shape)
print('test_ratings shape: ', test_ratings.shape)

users shape:  (68092, 6)
books shape:  (149570, 11)
train_ratings shape:  (306795, 3)
test_ratings shape:  (76699, 3)

In [7]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149570 entries, 0 to 149569
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   isbn                 149570 non-null  object
 1   book_title           149570 non-null  object
 2   book_author          149570 non-null  object
 3   year_of_publication  149570 non-null  float64
 4   publisher            149570 non-null  object
 5   img_url              149570 non-null  object
 6   language             82343 non-null   object
 7   category             80719 non-null   object
 8   summary              82343 non-null   object
 9   img_path             107768 non-null  object
 10  category_high        149570 non-null  object
dtypes: float64(1), object(10)
memory usage: 12.6+ MB

In [8]:
books6 = pd.read_csv(data_path + 'v6/books.csv')

In [9]:
books6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149570 entries, 0 to 149569
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   isbn                 149570 non-null  object
 1   book_title           149570 non-null  object
 2   book_author          149569 non-null  object
 3   year_of_publication  149570 non-null  float64
 4   publisher            149570 non-null  object
 5   img_url              149570 non-null  object
 6   language             149570 non-null  object
 7   category             80719 non-null   object
 8   summary              82343 non-null   object
 9   img_path             107768 non-null  object
 10  category_high        149570 non-null  object
 11  book_count_na        149570 non-null  int64
 12  book_rating_count    149570 non-null  float64
 13  book_rating_mean     149570 non-null  float64
dtypes: float64(3), int64(1), object(10)
memory usage: 16.0+ MB

In [10]:
final_books = books.merge(books6[['isbn', 'book_count_na', 'book_rating_count', 'book_rating_mean']], how='left', on='isbn')
final_books

,isbn,book_title,book_author,year_of_publication,publisher,img_url,language,category,summary,img_path,category_high,book_count_na,book_rating_count,book_rating_mean
0,0002005018,Clara Callan,Richard Bruce Wright,2001.0,Collins,http://images.amazon.com/images/P/0002005018.0...,en,actresses,"In a small town in Canada, Clara Callan reluct...",images/0002005018.01.THUMBZZZ.jpg,ficti,0,7.0,6.857143
1,0060973129,Decision in Normandy,Carlo D'Este,1991.0,Perennial,http://images.amazon.com/images/P/0060973129.0...,en,1940 1949,"Here, for the first time in paperback, is an o...",NaN,ficti,1,1.0,8.000000
2,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999.0,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,en,medical,"Describes the great flu epidemic of 1918, an o...",images/0374157065.01.THUMBZZZ.jpg,ficti,0,5.0,7.600000
3,0399135782,The Kitchen God's Wife,Amy Tan,1991.0,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,en,fiction,A Chinese immigrant who is convinced she is dy...,NaN,ficti,1,14.0,7.571429
4,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000.0,Berkley Publishing Group,http://images.amazon.com/images/P/0425176428.0...,en,history,"Essays by respected military historians, inclu...",images/0425176428.01.THUMBZZZ.jpg,ficti,0,1.0,8.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149565,067161746X,The Bachelor Home Companion: A Practical Guide...,P.J. O'Rourke,1987.0,Pocket,http://images.amazon.com/images/P/067161746X.0...,en,humor,A tongue-in-cheek survival guide for single pe...,NaN,humor wit,1,1.0,6.000000
149566,0767907566,All Elevations Unknown: An Adventure in the He...,Sam Lightner,2001.0,Broadway Books,http://images.amazon.com/images/P/0767907566.0...,en,nature,A daring twist on the travel-adventure genre t...,images/0767907566.01.THUMBZZZ.jpg,ficti,0,0.0,7.000000
149567,0884159221,Why stop?: A guide to Texas historical roadsid...,Claude Dooley,1985.0,Bridge Publications,http://images.amazon.com/images/P/0884159221.0...,NaN,NaN,NaN,NaN,ficti,3,1.0,7.000000
149568,0912333022,The Are You Being Served? Stories: 'Camping In...,Jeremy Lloyd,1997.0,Pub Group West,http://images.amazon.com/images/P/0912333022.0...,en,fiction,These hilarious stories by the creator of publ...,images/0912333022.01.THUMBZZZ.jpg,ficti,0,1.0,7.000000
149569,1569661057,"Dallas Street Map Guide and Directory, 2000 Ed...",Mapsco,1999.0,Soho Press,http://images.amazon.com/images/P/1569661057.0...,NaN,NaN,NaN,images/1569661057.01.THUMBZZZ.jpg,ficti,2,1.0,10.000000

In [12]:
final_books.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149570 entries, 0 to 149569
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   isbn                 149570 non-null  object
 1   book_title           149570 non-null  object
 2   book_author          149570 non-null  object
 3   year_of_publication  149570 non-null  float64
 4   publisher            149570 non-null  object
 5   img_url              149570 non-null  object
 6   language             82343 non-null   object
 7   category             80719 non-null   object
 8   summary              82343 non-null   object
 9   img_path             107768 non-null  object
 10  category_high        149570 non-null  object
 11  book_count_na        149570 non-null  int64
 12  book_rating_count    149570 non-null  float64
 13  book_rating_mean     149570 non-null  float64
dtypes: float64(3), int64(1), object(10)
memory usage: 17.1+ MB

In [13]:
final_books.to_csv(data_path + 'v8/books.csv', index=False)